#include <Arduino.h>

enum PinDefinicje
{
    TOF_SCL = D1,   // TIME OF FLIGHT - SCL PIN
    TOF_SDA = D2,   // TIME OF FLIGHT - SDA PIN
    IR_OUT = D3,    // SYGNAŁ CZUJNIKA IR DETEKCJI PRZESZKODY
    LED_RED = D6,   // PIN KOLORU CZERWONEGO
    LED_GREEN = D7, // PIN KOLORU ZIELONEGO
    LED_BLUE = D8   // PIN KOLORU NIEBIESKIEGO
};
